### ISSUE TITLE
Expression of AND in Chinese in 古代中国逻辑新说

### ISSUE THREAD

**Issue by weikengchen** [gjoncas/Working-Papers#1]
I think the “和” here is not correct.

由此各种各样的逻辑方法如雨后春笋，层出不穷，如模态逻辑、时序逻辑、认知逻辑、**_和_**模糊逻辑等。

also,

本文分为三个部分，即《易经》的数学、名家的辩论、**_和_**佛教的悖论。

Example: 
我们要成为有畅想、有道德、有文化、有纪律的“四有”新人。
军阀、官僚、土豪、劣绅是地主阶级的政治代表。

**Comment by liyishuai** [comment]
Reference: [General rules for punctuation](http://www.moe.gov.cn/s78/A19/yxs_left/moe_810/s230/201001/t20100115_75611.html), GB/T 15834-2011, Chapter 4.5.3.1

**Comment by gjoncas** [comment]
Thanks guys

I asked a translator, who pointed out [this site](http://www.njliaohua.com/lhd_1phg8350yr1ujtp7zfs8_1.html), which says:

> 3、多个并列词语，前面的之间用顿号，最后两个词语之间用“和”或“及”等。并列词语中如果有连词“和、与、及、或、或者”等，就不必再用顿号。

So I'll get rid of the final comma and keep the 和.

**Comment by weikengchen** [comment]
I think we still need to keep this issue.

from my experience, "多个并列词语，前面的之间用顿号，最后两个词语之间用“和”或“及”等。" is not what we do in practice.

Will collect my evidence.

**Comment by Eleanor-Li** [comment]
Hi honey,

How is your class going? You are in the middle of the money and banking class right? Is it challenging?

Btw, in case you will somehow check your email, can you please tell me where is the needle? I can't find it on the shelf you usually put it on.

Sleepy Nora

**Comment by liyishuai** [comment]
@Eleanor-Li Is your comment related to this issue?
If not, please move the discussion elsewhere. Thank you.

**Comment by Eleanor-Li** [comment]
@liyishuai hi, I just removed the comment and sorry for the inconvenience. Btw, actually, your last comment is not relevant either. If you please check the document you cited, there is no item to this specific discussion.

**Comment by Eleanor-Li** [comment]
@gjoncas hihihi, check your email please~
